server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kaoshi?serverTimezone=CST&characterEncoding=UTF-8
    username: root
    password: w123


jpa:
  #自动创建 | 更新  | 验证数据库表结构
  hibernate:
    ddl-auto: update
  # 设置数据库引擎为InnoDB
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  #  打印SQL
  show-sql: true
